# CMake generated Testfile for 
# Source directory: /mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test
# Build directory: /mnt/d/ClionProject/KaleidoscopeLanguage/build_release/test/run_test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(hello_world_run_test "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/bin/kalecc" "-i" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/origin_test_case/hello_world.k" "-r" "-o" "hello_world" "--check-input" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/hello_world")
set_tests_properties(hello_world_run_test PROPERTIES  WORKING_DIRECTORY "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/test/run_test" _BACKTRACE_TRIPLES "/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/CMakeLists.txt;15;add_test;/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/CMakeLists.txt;0;")
add_test(test_for1_run_test "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/bin/kalecc" "-i" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/origin_test_case/test_for1.k" "-r" "-o" "test_for1" "--check-input" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/test_for1")
set_tests_properties(test_for1_run_test PROPERTIES  WORKING_DIRECTORY "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/test/run_test" _BACKTRACE_TRIPLES "/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/CMakeLists.txt;15;add_test;/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/CMakeLists.txt;0;")
add_test(test_type_run_test "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/bin/kalecc" "-i" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/origin_test_case/test_type.k" "-r" "-o" "test_type" "--check-input" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/test_type")
set_tests_properties(test_type_run_test PROPERTIES  WORKING_DIRECTORY "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/test/run_test" _BACKTRACE_TRIPLES "/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/CMakeLists.txt;15;add_test;/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/CMakeLists.txt;0;")
add_test(test_add_run_test "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/bin/kalecc" "-i" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/origin_test_case/test_add.k" "-r" "-o" "test_add" "--check-input" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/test_add")
set_tests_properties(test_add_run_test PROPERTIES  WORKING_DIRECTORY "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/test/run_test" _BACKTRACE_TRIPLES "/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/CMakeLists.txt;15;add_test;/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/CMakeLists.txt;0;")
add_test(test_fibonacci_run_test "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/bin/kalecc" "-i" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/origin_test_case/test_fibonacci.k" "-r" "-o" "test_fibonacci" "--check-input" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/test_fibonacci")
set_tests_properties(test_fibonacci_run_test PROPERTIES  WORKING_DIRECTORY "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/test/run_test" _BACKTRACE_TRIPLES "/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/CMakeLists.txt;15;add_test;/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/CMakeLists.txt;0;")
add_test(test_for_int_run_test "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/bin/kalecc" "-i" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/origin_test_case/test_for_int.k" "-r" "-o" "test_for_int" "--check-input" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/test_for_int")
set_tests_properties(test_for_int_run_test PROPERTIES  WORKING_DIRECTORY "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/test/run_test" _BACKTRACE_TRIPLES "/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/CMakeLists.txt;15;add_test;/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/CMakeLists.txt;0;")
add_test(test_for_double_run_test "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/bin/kalecc" "-i" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/origin_test_case/test_for_double.k" "-r" "-o" "test_for_double" "--check-input" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/test_for_double")
set_tests_properties(test_for_double_run_test PROPERTIES  WORKING_DIRECTORY "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/test/run_test" _BACKTRACE_TRIPLES "/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/CMakeLists.txt;15;add_test;/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/CMakeLists.txt;0;")
add_test(test_while_double_run_test "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/bin/kalecc" "-i" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/origin_test_case/test_while_double.k" "-r" "-o" "test_while_double" "--check-input" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/test_while_double")
set_tests_properties(test_while_double_run_test PROPERTIES  WORKING_DIRECTORY "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/test/run_test" _BACKTRACE_TRIPLES "/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/CMakeLists.txt;15;add_test;/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/CMakeLists.txt;0;")
add_test(test_while_int_run_test "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/bin/kalecc" "-i" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/origin_test_case/test_while_int.k" "-r" "-o" "test_while_int" "--check-input" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/test_while_int")
set_tests_properties(test_while_int_run_test PROPERTIES  WORKING_DIRECTORY "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/test/run_test" _BACKTRACE_TRIPLES "/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/CMakeLists.txt;15;add_test;/mnt/d/ClionProject/KaleidoscopeLanguage/test/run_test/CMakeLists.txt;0;")
