# CMake generated Testfile for 
# Source directory: /mnt/d/ClionProject/KaleidoscopeLanguage/test/parser_test
# Build directory: /mnt/d/ClionProject/KaleidoscopeLanguage/build_release/test/parser_test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(hello_world_parser_test "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/bin/kalecc" "--only-parse" "-i" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/origin_test_case/hello_world.k")
set_tests_properties(hello_world_parser_test PROPERTIES  WORKING_DIRECTORY "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/test/parser_test" _BACKTRACE_TRIPLES "/mnt/d/ClionProject/KaleidoscopeLanguage/test/parser_test/CMakeLists.txt;15;add_test;/mnt/d/ClionProject/KaleidoscopeLanguage/test/parser_test/CMakeLists.txt;0;")
add_test(test_fibonacci_parser_test "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/bin/kalecc" "--only-parse" "-i" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/origin_test_case/test_fibonacci.k")
set_tests_properties(test_fibonacci_parser_test PROPERTIES  WORKING_DIRECTORY "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/test/parser_test" _BACKTRACE_TRIPLES "/mnt/d/ClionProject/KaleidoscopeLanguage/test/parser_test/CMakeLists.txt;15;add_test;/mnt/d/ClionProject/KaleidoscopeLanguage/test/parser_test/CMakeLists.txt;0;")
add_test(test_for_double_parser_test "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/bin/kalecc" "--only-parse" "-i" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/origin_test_case/test_for_double.k")
set_tests_properties(test_for_double_parser_test PROPERTIES  WORKING_DIRECTORY "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/test/parser_test" _BACKTRACE_TRIPLES "/mnt/d/ClionProject/KaleidoscopeLanguage/test/parser_test/CMakeLists.txt;15;add_test;/mnt/d/ClionProject/KaleidoscopeLanguage/test/parser_test/CMakeLists.txt;0;")
add_test(test_for_int_parser_test "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/bin/kalecc" "--only-parse" "-i" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/origin_test_case/test_for_int.k")
set_tests_properties(test_for_int_parser_test PROPERTIES  WORKING_DIRECTORY "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/test/parser_test" _BACKTRACE_TRIPLES "/mnt/d/ClionProject/KaleidoscopeLanguage/test/parser_test/CMakeLists.txt;15;add_test;/mnt/d/ClionProject/KaleidoscopeLanguage/test/parser_test/CMakeLists.txt;0;")
add_test(test_for1_parser_test "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/bin/kalecc" "--only-parse" "-i" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/origin_test_case/test_for1.k")
set_tests_properties(test_for1_parser_test PROPERTIES  WORKING_DIRECTORY "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/test/parser_test" _BACKTRACE_TRIPLES "/mnt/d/ClionProject/KaleidoscopeLanguage/test/parser_test/CMakeLists.txt;15;add_test;/mnt/d/ClionProject/KaleidoscopeLanguage/test/parser_test/CMakeLists.txt;0;")
add_test(test_add_parser_test "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/bin/kalecc" "--only-parse" "-i" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/origin_test_case/test_add.k")
set_tests_properties(test_add_parser_test PROPERTIES  WORKING_DIRECTORY "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/test/parser_test" _BACKTRACE_TRIPLES "/mnt/d/ClionProject/KaleidoscopeLanguage/test/parser_test/CMakeLists.txt;15;add_test;/mnt/d/ClionProject/KaleidoscopeLanguage/test/parser_test/CMakeLists.txt;0;")
add_test(test_type_parser_test "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/bin/kalecc" "--only-parse" "-i" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/origin_test_case/test_type.k")
set_tests_properties(test_type_parser_test PROPERTIES  WORKING_DIRECTORY "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/test/parser_test" _BACKTRACE_TRIPLES "/mnt/d/ClionProject/KaleidoscopeLanguage/test/parser_test/CMakeLists.txt;15;add_test;/mnt/d/ClionProject/KaleidoscopeLanguage/test/parser_test/CMakeLists.txt;0;")
add_test(test_while_double_parser_test "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/bin/kalecc" "--only-parse" "-i" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/origin_test_case/test_while_double.k")
set_tests_properties(test_while_double_parser_test PROPERTIES  WORKING_DIRECTORY "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/test/parser_test" _BACKTRACE_TRIPLES "/mnt/d/ClionProject/KaleidoscopeLanguage/test/parser_test/CMakeLists.txt;15;add_test;/mnt/d/ClionProject/KaleidoscopeLanguage/test/parser_test/CMakeLists.txt;0;")
add_test(test_while_int_parser_test "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/bin/kalecc" "--only-parse" "-i" "/mnt/d/ClionProject/KaleidoscopeLanguage/test/origin_test_case/test_while_int.k")
set_tests_properties(test_while_int_parser_test PROPERTIES  WORKING_DIRECTORY "/mnt/d/ClionProject/KaleidoscopeLanguage/build_release/test/parser_test" _BACKTRACE_TRIPLES "/mnt/d/ClionProject/KaleidoscopeLanguage/test/parser_test/CMakeLists.txt;15;add_test;/mnt/d/ClionProject/KaleidoscopeLanguage/test/parser_test/CMakeLists.txt;0;")
